min_reviewers: 0

ignore:
  - M101

components:
  - access
  - accounts
  - admin
  - alerts
  - annotations
  - apikeys
  - archiver
  - arxiv
  - assets
  - authorlist
  - authorprofiles
  - authors
  - babel
  - baskets
  - bulletin
  - cache
  - checker
  - celery
  - circulation
  - classifier
  - cloudconnector
  - collect
  - collections
  - comments
  - communities
  - config
  - converter
  - crossref
  - dashboard
  - debug_toolbar
  - deposit
  - docker
  - docs
  - documentation
  - documents
  - editor
  - elasticsearch
  - email
  - encoder
  - exporter
  - fixtures
  - formatter
  - fs
  - global
  - gravatar
  - groups
  - i18n
  - indexer
  - installation
  - jasmine
  - jsonalchemy
  - knowledge
  - kwalitee
  - legacy
  - linkbacks
  - logging
  - login
  - matcher
  - menu
  - merger
  - messages
  - mixer
  - multimedia
  - oaiharvester
  - oairepository
  - oauth2server
  - oauthclient
  - pages
  - pdfchecker
  - pidstore
  - previewer
  - principal
  - ranker
  - records
  - redirector
  - refextract
  - registry
  - restful
  - scheduler
  - script
  - search
  - sequencegenerator
  - session
  - sorter
  - sqlalchemy
  - sslify
  - sso
  - statistics
  - submit
  - sword
  - tags
  - template
  - textminer
  - tickets
  - travis
  - unapi
  - upgrader
  - uploader
  - version
  - webhooks
  - workflows
