#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# This file is part of CERN Document Server.
# Copyright (C) 2019 CERN.
#
# CERN Document Server is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# CERN Document Server is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CERN Document Server; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

set -e

CWD=`pwd`

requirements_file=${1:-'requirements.pinned.txt'}

pip install -r $requirements_file
pip install -e .[all]

npm update
npm install \
    node-sass@3.8.0 \
    clean-css@3.4.24 \
    uglify-js requirejs

# Setup and build assets
cds npm
# static_folder=$(cds shell --no-term-title -c "print(app.static_folder)")
# cd $static_folder
cd ${VIRTUAL_ENV}/var/instance/static
npm install
cd ${CWD}
cds collect -v
cds assets build
cds webpack buildall
