#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# This file is part of CERN Document Server.
# Copyright (C) 2019 CERN.
#
# CERN Document Server is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# CERN Document Server is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CERN Document Server; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

set -e

script_path=$(dirname "$0")

export FLASK_ENV=development
# Start Worker and Server
celery worker -A cds.celery -l INFO & pid_celery=$!

cds run --reload --with-threads \
    --cert "$script_path"/../docker/nginx/test.crt \
    --key "$script_path"/../docker/nginx/test.key & pid_server=$!

trap 'kill $pid_celery $pid_server &>/dev/null' EXIT

wait $pid_celery $pid_server
