# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CERN.
#
# Invenio App RDM is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [2.7, 3.5]

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt-get install ffmpeg

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Use Node.js 8.x
        uses: actions/setup-node@v1
        with:
          node-version: 8.x

      - name: Install global Node packages
        run: |
          ./scripts/setup-npm.sh
          rm -f package-lock.json

      - name: Generate dependencies
        run: |
          python -m pip install "pip>=20,<21" setuptools py
          python -m pip install wheel coveralls requirements-builder configparser
          pip freeze
          cp requirements.pinned.txt .ci-${{ matrix.python-version }}-requirements.txt

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.ci-${{ matrix.python-version }}-requirements.txt') }}

      - name: Install dependencies
        run: |
          export VIRTUAL_ENV=${pythonLocation}
          ./scripts/bootstrap .ci-${{ matrix.python-version }}-requirements.txt
          pip freeze
          docker --version
          docker-compose --version

      - name: Run tests
        run: |
          docker-compose up -d
          ./run-tests.sh
